-- 테이블 전체 드롭 명령어 수집용 SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE "GAME" CASCADE CONSTRAINTS;
DROP TABLE "HEART" CASCADE CONSTRAINTS;
DROP TABLE "FRIEND" CASCADE CONSTRAINTS;
DROP TABLE "GAME_RANK" CASCADE CONSTRAINTS;
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "CHARACTER_SKIN" CASCADE CONSTRAINTS;
DROP TABLE "DISABLED_MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "CHATTING" CASCADE CONSTRAINTS;
DROP TABLE "CHARACTER" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
DROP TABLE "LOGIN_API" CASCADE CONSTRAINTS;
DROP TABLE "REPORT" CASCADE CONSTRAINTS;
DROP TABLE "CHATTINGROOM" CASCADE CONSTRAINTS;

DROP sequence "SEQ_BOARD";
DROP sequence "SEQ_CHAT";
DROP sequence "SEQ_NOTICE";
DROP sequence "SEQ_REPORT";
DROP sequence "SEQ_SKIN";

CREATE TABLE "GAME" (
	"GAME_TITLE"	VARCHAR2(20)		NOT NULL,
	"PAYMENT_COIN"	NUMBER	DEFAULT 100	NOT NULL
);

COMMENT ON COLUMN "GAME"."GAME_TITLE" IS '게임명(pk)';

COMMENT ON COLUMN "GAME"."PAYMENT_COIN" IS '클리어시 지급 코인량';

CREATE TABLE "HEART" (
	"RECEIVE_ID"	VARCHAR2(20)		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "HEART"."RECEIVE_ID" IS '호감도를 받은 사람(fk)';

COMMENT ON COLUMN "HEART"."USER_ID" IS '호감도를 준 사람(fk)';

COMMENT ON COLUMN "HEART"."CREATE_DATE" IS '호감도 준 시간';

CREATE TABLE "FRIEND" (
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"FRIEND_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "FRIEND"."USER_ID" IS '본인ID(pk)';

COMMENT ON COLUMN "FRIEND"."FRIEND_ID" IS '친구ID(pk)';

CREATE TABLE "GAME_RANK" (
	"GAME_TITLE"	VARCHAR2(20)		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"GAME_SCORE"	NUMBER		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "GAME_RANK"."GAME_TITLE" IS '게임이름(pk)';

COMMENT ON COLUMN "GAME_RANK"."USER_ID" IS '유저ID(pk)';

COMMENT ON COLUMN "GAME_RANK"."GAME_SCORE" IS '가장높은점수';

COMMENT ON COLUMN "GAME_RANK"."CREATE_DATE" IS '날짜';

CREATE TABLE "MEMBER" (
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_PWD"	NVARCHAR2(300)		NOT NULL,
	"NICKNAME"	NVARCHAR2(8)	UNIQUE	NOT NULL,
	"STATUS"	CHAR(1)  DEFAULT 'Y' CHECK( STATUS IN('Y' , 'N' , 'X'))	NOT NULL,
	"SKIN_ID"	NUMBER	DEFAULT '0'	NOT NULL,
	"COIN"	NUMBER(4)	DEFAULT 500	NOT NULL,
	"SELF_INFO"	VARCHAR2(300)		NULL,
	"GENDER"	CHAR(1) DEFAULT 'N' CHECK(GENDER IN('M','W','N')) NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."USER_ID" IS '유저ID(pk)';

COMMENT ON COLUMN "MEMBER"."USER_PWD" IS '암호화된 PW';

COMMENT ON COLUMN "MEMBER"."NICKNAME" IS '닉네임(UNIQUEKEY)';

COMMENT ON COLUMN "MEMBER"."SKIN_ID" IS '현재 적용중인 스킨 ID';

COMMENT ON COLUMN "MEMBER"."COIN" IS '유저가 가진 코인';

COMMENT ON COLUMN "MEMBER"."GENDER" IS 'CHECK(M,W,N)';

COMMENT ON COLUMN "MEMBER"."SELF_INFO" IS '유저 자기소개';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '디폴트 현재시간';

COMMENT ON COLUMN "MEMBER"."STATUS" IS '계정상태(Y, N, X)';

CREATE TABLE "CHARACTER_SKIN" (
	"SKIN_ID"	NUMBER  NOT NULL,
	"SAVE_ROOT"	NVARCHAR2(300)		NOT NULL,
	"CHARACTER_PRICE"	NUMBER	DEFAULT 300	NOT NULL
);

COMMENT ON COLUMN "CHARACTER_SKIN"."SKIN_ID" IS '시퀀스자동생성(pk)';

COMMENT ON COLUMN "CHARACTER_SKIN"."SAVE_ROOT" IS '폴더경로';

COMMENT ON COLUMN "CHARACTER_SKIN"."CHARACTER_PRICE" IS '캐릭터 가격 코인금액';

CREATE TABLE "DISABLED_MEMBER" (
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"STATUS"	CHAR(1) CHECK( STATUS IN('X', 'N'))	NOT NULL,
	"CANCELLATION_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "DISABLED_MEMBER"."USER_ID" IS '유저ID(pk)';

COMMENT ON COLUMN "DISABLED_MEMBER"."STATUS" IS '비활성화 종류(N, X)';

COMMENT ON COLUMN "DISABLED_MEMBER"."CANCELLATION_DATE" IS '탈퇴 날짜';

CREATE TABLE "CHATTING" (
	"CHAT_NO"	NUMBER	NOT NULL ,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"RECEIVE_ID"	VARCHAR2(20)		NOT NULL,
	"CONTENT"	NVARCHAR2(50)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "CHATTING"."CHAT_NO" IS '시퀀스자동생성(pk)';

COMMENT ON COLUMN "CHATTING"."USER_ID" IS '보낸사람ID(fk)';

COMMENT ON COLUMN "CHATTING"."RECEIVE_ID" IS '받는사람ID(fk)';

COMMENT ON COLUMN "CHATTING"."CONTENT" IS '채팅내용(30글자)';

COMMENT ON COLUMN "CHATTING"."CREATE_DATE" IS '채팅작성시간';


CREATE TABLE "CHATTINGROOM" (
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"RECEIVE_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "CHATTINGROOM"."USER_ID" IS '본인ID(pk)';

COMMENT ON COLUMN "CHATTINGROOM"."RECEIVE_ID" IS '상대ID(pk)';


CREATE TABLE "CHARACTER" (
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"SKIN_ID"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHARACTER"."USER_ID" IS '유저ID(pk)';

COMMENT ON COLUMN "CHARACTER"."SKIN_ID" IS '캐릭터 스킨ID(pk)';

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER	NOT NULL,
	"NOTICE_TITLE"	NVARCHAR2(100)		NOT NULL,
	"NOTICE_CONTENT"	NVARCHAR2(300)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '시퀀스자동생성(pk)';

COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '공지사항 제목';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '공지사항 내용';

COMMENT ON COLUMN "NOTICE"."CREATE_DATE" IS '등록 시간';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER	NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"RECEIVE_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(15)		NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(500)		NOT NULL,
	"SECRET"	CHAR(1) DEFAULT 'N'	CHECK( SECRET IN('N', 'Y'))	NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '시퀀스자동생성(pk)';

COMMENT ON COLUMN "BOARD"."USER_ID" IS '작성자ID(fk)';

COMMENT ON COLUMN "BOARD"."RECEIVE_ID" IS '받는사람ID(fk)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '방명록 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '방명록 내용';

COMMENT ON COLUMN "BOARD"."SECRET" IS 'CHECK(N,Y)';

COMMENT ON COLUMN "BOARD"."CREATE_DATE" IS '작성 시간';

CREATE TABLE "LOGIN_API" (
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"API_KIND"	NVARCHAR2(5)		NOT NULL,
	"API_KEY"	NVARCHAR2(300)		NOT NULL
);

COMMENT ON COLUMN "LOGIN_API"."USER_ID" IS '유저ID(pk)';

COMMENT ON COLUMN "LOGIN_API"."API_KIND" IS '구글/카카오';

COMMENT ON COLUMN "LOGIN_API"."API_KEY" IS '받아온키';

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER	NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"RECEIVE_ID"	VARCHAR2(20)		NOT NULL,
	"REPORT_TITLE"	NVARCHAR2(20)		NOT NULL,
	"REPORT_CONTENT"	NVARCHAR2(300)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '시퀀스자동생성(pk)';

COMMENT ON COLUMN "REPORT"."USER_ID" IS '신고자ID(fk)';

COMMENT ON COLUMN "REPORT"."RECEIVE_ID" IS '대상자ID(fk)';

COMMENT ON COLUMN "REPORT"."REPORT_TITLE" IS '신고 제목';

COMMENT ON COLUMN "REPORT"."REPORT_CONTENT" IS '신고 내용';

COMMENT ON COLUMN "REPORT"."CREATE_DATE" IS '신고 등록 시간';

ALTER TABLE "GAME" ADD CONSTRAINT "PK_GAME" PRIMARY KEY (
	"GAME_TITLE"
);

ALTER TABLE "FRIEND" ADD CONSTRAINT "PK_FRIEND" PRIMARY KEY (
	"USER_ID",
	"FRIEND_ID"
);

ALTER TABLE "GAME_RANK" ADD CONSTRAINT "PK_GAME_RANK" PRIMARY KEY (
	"GAME_TITLE",
	"USER_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "CHARACTER_SKIN" ADD CONSTRAINT "PK_CHARACTER_SKIN" PRIMARY KEY (
	"SKIN_ID"
);

ALTER TABLE "DISABLED_MEMBER" ADD CONSTRAINT "PK_DISABLED_MEMBER" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "CHATTING" ADD CONSTRAINT "PK_CHATTING" PRIMARY KEY (
	"CHAT_NO"
);

ALTER TABLE "CHATTINGROOM" ADD CONSTRAINT "PK_CHATTINGROOM" PRIMARY KEY (
	"USER_ID",
	"RECEIVE_ID"
);

ALTER TABLE "CHARACTER" ADD CONSTRAINT "PK_CHARACTER" PRIMARY KEY (
	"USER_ID",
	"SKIN_ID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "LOGIN_API" ADD CONSTRAINT "PK_LOGIN_API" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "HEART" ADD CONSTRAINT "FK_MEMBER_TO_HEART_1" FOREIGN KEY (
	"RECEIVE_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "HEART" ADD CONSTRAINT "FK_MEMBER_TO_HEART_2" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "FRIEND" ADD CONSTRAINT "FK_MEMBER_TO_FRIEND_1" FOREIGN KEY (
	"FRIEND_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "FRIEND" ADD CONSTRAINT "FK_MEMBER_TO_FRIEND_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "GAME_RANK" ADD CONSTRAINT "FK_GAME_TO_GAME_RANK_1" FOREIGN KEY (
	"GAME_TITLE"
)
REFERENCES "GAME" (
	"GAME_TITLE"
) ON DELETE CASCADE;

ALTER TABLE "GAME_RANK" ADD CONSTRAINT "FK_MEMBER_TO_GAME_RANK_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_CHARACTER_SKIN_TO_MEMBER_1" FOREIGN KEY (
	"SKIN_ID"
)
REFERENCES "CHARACTER_SKIN" (
	"SKIN_ID"
) ON DELETE SET NULL;

ALTER TABLE "DISABLED_MEMBER" ADD CONSTRAINT "FK_MEMBER_TO_DISABLED_MEMBER_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "CHATTING" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "CHATTING" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_2" FOREIGN KEY (
	"RECEIVE_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;



ALTER TABLE "CHATTINGROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATTINGROOM_1" FOREIGN KEY (
	"RECEIVE_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
)ON DELETE CASCADE;


ALTER TABLE "CHATTINGROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATTINGROOM_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
)ON DELETE CASCADE;




ALTER TABLE "CHARACTER" ADD CONSTRAINT "FK_MEMBER_TO_CHARACTER_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "CHARACTER" ADD CONSTRAINT "FK_CHARACTER_SKIN_TO_CHARACTER_1" FOREIGN KEY (
	"SKIN_ID"
)
REFERENCES "CHARACTER_SKIN" (
	"SKIN_ID"
) ON DELETE CASCADE;

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_2" FOREIGN KEY (
	"RECEIVE_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "LOGIN_API" ADD CONSTRAINT "FK_MEMBER_TO_LOGIN_API_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_2" FOREIGN KEY (
	"RECEIVE_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
) ON DELETE CASCADE;

-- 시퀀스 생성 구역

CREATE SEQUENCE SEQ_NOTICE
			INCREMENT BY 1
			START WITH 1
			NOCYCLE;


CREATE SEQUENCE SEQ_BOARD
			INCREMENT BY 1
			START WITH 1
			NOCYCLE;


CREATE SEQUENCE SEQ_SKIN
			INCREMENT BY 1
			START WITH 1
			NOCYCLE;

			
CREATE SEQUENCE SEQ_REPORT
			INCREMENT BY 1
			START WITH 1
			NOCYCLE;


CREATE SEQUENCE SEQ_CHAT
			INCREMENT BY 1
			START WITH 1
			NOCYCLE;