-- 1
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

-- 2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 3
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '강원도%') AND STUDENT_NO LIKE '9%'
ORDER BY STUDENT_NAME;

-- 4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO = 005
ORDER BY PROFESSOR_SSN;

-- 5
SELECT STUDENT_NO, TO_CHAR(POINT, '9.99')
FROM TB_GRADE
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY 2 DESC, 1 ASC;

-- 6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2 ASC;

SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY 2 ASC;

-- 7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM  TB_CLASS               
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY DEPARTMENT_NO ASC;

-- 8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO) -- 과목 번호
JOIN TB_PROFESSOR USING(PROFESSOR_NO) -- 교수 번호
ORDER BY TB_CLASS.DEPARTMENT_NO, 2 ASC; 

SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR CP ON (CP.CLASS_NO = C.CLASS_NO)
JOIN TB_PROFESSOR P ON (P.PROFESSOR_NO = CP.PROFESSOR_NO)
ORDER BY DEPARTMENT_NO, 2 ASC;

-- 9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO) -- 과목 번호
JOIN TB_PROFESSOR P USING(PROFESSOR_NO) -- 교수 번호
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.CATEGORY = '인문사회'
ORDER BY TB_CLASS.DEPARTMENT_NO, 2 ASC; 

SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO) -- 과목 번호
JOIN TB_PROFESSOR P USING(PROFESSOR_NO) -- 교수 번호
WHERE P.DEPARTMENT_NO IN (
    SELECT DEPARTMENT_NO FROM TB_DEPARTMENT
    WHERE CATEGORY = '인문사회')
ORDER BY TB_CLASS.DEPARTMENT_NO, 2 ASC;

-- 10


-- 18
SELECT STUDENT_NO, STUDENT_NAME
FROM(
    SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT) AS POINT
    FROM TB_STUDENT
    JOIN TB_GRADE USING(STUDENT_NO)
    WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO 
                           FROM TB_DEPARTMENT 
                           WHERE DEPARTMENT_NAME = '국어국문학과')
    GROUP BY STUDENT_NO, STUDENT_NAME
    ORDER BY POINT DESC
)
WHERE ROWNUM = 1;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO 
                       FROM TB_DEPARTMENT 
                       WHERE DEPARTMENT_NAME = '국어국문학과')
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (
                      SELECT MAX(AVG(POINT))
                      FROM TB_STUDENT
                      JOIN TB_GRADE USING(STUDENT_NO)
                      WHERE DEPARTMENT_NO = '001'
                      GROUP BY STUDENT_NO
                     );