-- 1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE ASC;

-- 2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)<>3;

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE'___';

--3
SELECT PROFESSOR_NAME 교수이름, TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE(19 || SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYYMMDD')) / 12) 나이,
EXTRACT(YEAR FROM SYSDATE) - TO_NUMBER(19 || SUBSTR(PROFESSOR_SSN, 1, 2)) AS 연나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;

SELECT PROFESSOR_NAME 교수이름, FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(19 || SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYYMMDD')) / 12) 나이
    ,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 2, PROFESSOR_NAME;

-- 4
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) 이름
FROM TB_PROFESSOR;

-- 5 입학연도 - 태어난연도 = 재수생 구하기
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6)))> 19
ORDER BY STUDENT_NO ASC;

-- 6
SELECT TO_CHAR(TO_DATE('2020/12/25'), 'DAY')
FROM DUAL;

-- 7
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'), 'YYYY"년" MM"월" DD"일"'),
    TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'), 'YYYY"년" MM"월" DD"일"'),
    TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'RRRR"년" MM"월" DD"일"'),
    TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'RRRR"년" MM"월" DD"일"')
FROM DUAL;

-- 8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000;

SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

-- 9
SELECT ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10
SELECT DEPARTMENT_NO 학과번호,COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

SELECT (COUNT(*)-COUNT(COACH_PROFESSOR_NO)) AS "COUNT(*)"
FROM TB_STUDENT;

-- 12
SELECT SUBSTR(TERM_NO,1,4) "년도", ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE 
WHERE STUDENT_NO = 'A112113'
group by SUBSTR(TERM_NO,1,4);

-- 13
SELECT DEPARTMENT_NO 학과코드명, COUNT(1) "휴학생 수"
                            -- COUNT(DECODE(ABSENCE_YN, 'Y', 1, NULL))
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;

-- 14
SELECT STUDENT_NAME AS "동일 이름", COUNT(1) "동명이인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY 1 ASC;

-- 15
SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, 5, 2) 학기, ROUND(AVG(POINT), 1) 평균
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
ORDER BY 1;