-- 1
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CLASS_TYPE_NO TO 번호;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CLASS_TYPE_NAME TO 유형이름;
INSERT INTO TB_CLASS_TYPE
(
    SELECT 01, '전공필수'
    FROM DUAL
    UNION
    SELECT 02, '전공선택'
    FROM DUAL
    UNION
    SELECT 03, '교양필수'
    FROM DUAL
    UNION
    SELECT 04, '교양선택'
    FROM DUAL
    UNION
    SELECT 05, '논문지도'
    FROM DUAL
);

-- 2
CREATE TABLE TB_학생일반정보(학번, 학생이름, 주소)
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
   FROM TB_STUDENT;

-- 3
CREATE TABLE TB_국어국문학과(학번, 학생이름, 출생년도, 교수이름)
AS SELECT STUDENT_NO, STUDENT_NAME, TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN, 1, 6)), 'YYYY'), NVL(PROFESSOR_NAME, '지도교수없음')
   FROM TB_STUDENT S
   LEFT JOIN TB_PROFESSOR ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
   LEFT JOIN TB_DEPARTMENT D ON(D.DEPARTMENT_NO = S.DEPARTMENT_NO)
   WHERE DEPARTMENT_NAME = '국어국문학과';
 
-- 4
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY + CAPACITY * 0.1);

-- 5
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

-- 6
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

-- 7
UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = '200501' AND CLASS_NO =( 
                                         SELECT CLASS_NO
                                         FROM TB_CLASS
                                         WHERE CLASS_NAME = '피부생리학'
);

-- 8
DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (
                      SELECT STUDENT_NO
                      FROM TB_STUDENT
                      WHERE ABSENCE_YN = 'Y'
);